/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.83
 * Generated at: 2025-12-04 23:03:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.interweave.businessDaemon.*;
import java.util.*;

public final class BDConfiguratorA_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("com.interweave.businessDaemon");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 String refreshValue = request.getParameter("RefreshValue");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");

String brand = request.getParameter("PortalBrand");
if(brand==null){
brand="";
}
String solutions = request.getParameter("PortalSolutions");
if(solutions==null){
solutions="";
}
String brandSol = "";
if (brand != null && brand.length() > 0) {
	brandSol += "&PortalBrand=" + brand;
}
if (solutions != null && solutions.length() > 0) {
	brandSol += "&PortalSolutions=" + solutions;
}
String brandSol1 = "";
if (brand != null && brand.length() > 0) {
	brandSol1 += "?PortalBrand=" + brand;
}
if (solutions != null && solutions.length() > 0) {
	brandSol1 += ((brand != null && brand.length() > 0)?"&":"?") + "PortalSolutions=" + solutions;
}
if(ConfigContext.getRefresh() > 0L){ 
String rv = "10;url=BDConfiguratorA.jsp?RefreshValue=" + ConfigContext.getRefresh()+ brandSol;
      out.write("\r\n");
      out.write("<meta http-equiv=\"Refresh\" content=\"");
      out.print( rv);
      out.write('"');
      out.write('>');
}
      out.write("\r\n");
      out.write("<title>IM Admin Configurator Page</title>\r\n");
      out.write("<style>\r\n");
      out.write("<!--\r\n");
      out.write(".labels\r\n");
      out.write("   {\r\n");
      out.write("   color: black; font-family: Verdana; font-size: 10pt; font-style: normal; font-weight: bold;\r\n");
      out.write("   }\r\n");
      out.write(".tablelabels\r\n");
      out.write("   {\r\n");
      out.write("   color: black; font-family: Verdana; font-size: 8pt; font-style: normal; font-weight: bold;\r\n");
      out.write("   }\r\n");
      out.write(".table\r\n");
      out.write("   {\r\n");
      out.write("   color: black; font-family: Verdana; font-size: 8pt; font-style: normal; font-weight: normal;\r\n");
      out.write("   }\r\n");
      out.write(".tableitalic\r\n");
      out.write("   {\r\n");
      out.write("   color: black; font-family: Verdana; font-size: 8pt; font-style: italic; font-weight: normal;\r\n");
      out.write("   }\r\n");
      out.write("-->\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
 
if(ConfigContext.isAdminLoggedIn() || (refreshValue!=null && ConfigContext.getRefresh()>0L && ConfigContext.getRefresh()==Long.valueOf(refreshValue))){
ConfigContext.setAdminLoggedIn(false);

      out.write("\r\n");
      out.write("<table border=\"0\" cellpadding=\"0\" width=\"100%\" cellspacing=\"0\">\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td><img src=\"");
      out.print( "images" + ((brand==null || brand.equals(""))?"":("/" + brand)) + "/IT Banner.png");
      out.write("\" alt=\"Title\" align=\"left\" width=\"100%\" height=\"94\"/></td>\r\n");
      out.write("	</tr>\r\n");
      out.write("</table>\r\n");
      out.write("<table border=\"0\" cellpadding=\"3\" width=\"100%\" cellspacing=\"0\">\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td align=\"left\"><span style=\"color: black; font-family: Verdana; font-size: 15pt; font-style: normal; font-weight: bold\">InterWeave\r\n");
      out.write("		Integration Manager</span><br/>\r\n");
      out.write("		</td>\r\n");
      out.write("					<td align=\"right\"><a href='");
      out.print( "BDMinitor.jsp" + brandSol1);
      out.write("'	class=\"labels\" target=\"_blank\">IW Monitor</a></td>\r\n");
      out.write("					<td align=\"right\"><a href='");
      out.print( "LogoutServlet" + brandSol1);
      out.write("' target=\"_top\" class=\"labels\">Logout</a></td>\r\n");
      out.write("					<td align=\"right\"><a href='http://interweave.biz' class=\"labels\" target=\"_blank\">InterWeave</a></td>\r\n");
      out.write("				\r\n");
      out.write("	</tr>\r\n");
if(ConfigContext.isHosted() && (!ConfigContext.isSupportLoggedIn())){ 
      out.write("\r\n");
      out.write("	<tr bgcolor=\"#eeeeee\" align=\"right\">\r\n");
      out.write("		<td><form action=\"ProductDemoServlet\" method=\"post\" target=\"_top\">\r\n");
      out.write("				<input type=\"submit\" name=\"command\" value=\"Flow Assignment\" class=\"labels\"/>\r\n");
      out.write("<input type=\"hidden\" name=\"PortalBrand\" value=\"");
      out.print( brand);
      out.write("\"/>\r\n");
      out.write("<input type=\"hidden\" name=\"PortalSolutions\" value=\"");
      out.print( solutions);
      out.write("\"/>\r\n");
      out.write("<input type=\"hidden\" name=\"WhoAmI\" value=\"A\"/>\r\n");
      out.write("			</form>\r\n");
      out.write("		</td>\r\n");
      out.write("		<td>\r\n");
      out.write("			<form action=\"ProductDemoServlet\" method=\"post\" target=\"_top\">\r\n");
      out.write("				<input type=\"submit\" name=\"command\" value=\"List Users\" class=\"labels\" disabled=\"disabled\"/>\r\n");
      out.write("<input type=\"hidden\" name=\"PortalBrand\" value=\"");
      out.print( brand);
      out.write("\"/>\r\n");
      out.write("<input type=\"hidden\" name=\"PortalSolutions\" value=\"");
      out.print( solutions);
      out.write("\"/>\r\n");
      out.write("<input type=\"hidden\" name=\"WhoAmI\" value=\"A\"/>\r\n");
      out.write("			</form>\r\n");
      out.write("		</td>\r\n");
      out.write("		<td>\r\n");
      out.write("			<form action=\"ProductDemoServlet\" method=\"post\" target=\"_top\">\r\n");
      out.write("				<input type=\"submit\" name=\"command\" value=\"Stop and Save\" class=\"labels\"/>\r\n");
      out.write("<input type=\"hidden\" name=\"PortalBrand\" value=\"");
      out.print( brand);
      out.write("\"/>\r\n");
      out.write("<input type=\"hidden\" name=\"PortalSolutions\" value=\"");
      out.print( solutions);
      out.write("\"/>\r\n");
      out.write("<input type=\"hidden\" name=\"WhoAmI\" value=\"A\"/>\r\n");
      out.write("			</form>\r\n");
      out.write("		</td>\r\n");
      out.write("		<td>\r\n");
      out.write("			<form action=\"ProductDemoServlet\" method=\"post\" target=\"_top\">\r\n");
      out.write("				<input type=\"submit\" name=\"command\" value=\"Save\" class=\"labels\"/>\r\n");
      out.write("<input type=\"hidden\" name=\"PortalBrand\" value=\"");
      out.print( brand);
      out.write("\"/>\r\n");
      out.write("<input type=\"hidden\" name=\"PortalSolutions\" value=\"");
      out.print( solutions);
      out.write("\"/>\r\n");
      out.write("<input type=\"hidden\" name=\"WhoAmI\" value=\"A\"/>\r\n");
      out.write("			</form>\r\n");
      out.write("		</td>\r\n");
      out.write("		<td>\r\n");
      out.write("			<form action=\"ProductDemoServlet\" method=\"post\" target=\"_top\">\r\n");
      out.write("				<input type=\"submit\" name=\"command\" value=\"Restore\" class=\"labels\"/>\r\n");
      out.write("<input type=\"hidden\" name=\"PortalBrand\" value=\"");
      out.print( brand);
      out.write("\"/>\r\n");
      out.write("<input type=\"hidden\" name=\"PortalSolutions\" value=\"");
      out.print( solutions);
      out.write("\"/>\r\n");
      out.write("<input type=\"hidden\" name=\"WhoAmI\" value=\"A\"/>\r\n");
      out.write("			</form>\r\n");
      out.write("		</td>\r\n");
      out.write("	</tr>\r\n");
}
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("<form action=\"ProductDemoServlet\" method=\"post\" target=\"_top\">\r\n");
      out.write("<input type=\"hidden\" name=\"PortalBrand\" value=\"");
      out.print( brand);
      out.write("\"/>\r\n");
      out.write("<input type=\"hidden\" name=\"PortalSolutions\" value=\"");
      out.print( solutions);
      out.write("\"/>\r\n");
      out.write("<input type=\"hidden\" name=\"WhoAmI\" value=\"A\"/>\r\n");

if(ConfigContext.isHosted() && ((ConfigContext.getLoggedUserType()=='A') || (ConfigContext.getLoggedUserType()=='S')) && (!ConfigContext.isSupportLoggedIn())){ 
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<table border=\"0\" cellpadding=\"0\" class=\"labels\" cellspacing=\"0\" width=\"100%\">\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td>DB Driver</td>\r\n");
      out.write("			<td>\r\n");
      out.write("				<input type=\"text\" name=\"LocalDBDriver\" value='");
      out.print( ConfigContext.getHostedDriver());
      out.write("' size=\"60\" maxlength=\"80\"/>\r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td>DB DSN</td>\r\n");
      out.write("			<td>\r\n");
      out.write("				<input type=\"text\" name=\"LocalDBDSN\" value='");
      out.print( ConfigContext.getHostedURL());
      out.write("' size=\"60\" maxlength=\"80\"/>\r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td>DB User</td>\r\n");
      out.write("			<td>\r\n");
      out.write("				<input type=\"text\" name=\"LocalDBUser\" value='");
      out.print( ConfigContext.getHostedUser());
      out.write("' size=\"20\" maxlength=\"80\"/>\r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td>DB Password</td>\r\n");
      out.write("			<td>\r\n");
      out.write("				<input type=\"password\" name=\"LocalDBPassword\" value='");
      out.print( ConfigContext.getHostedPassword());
      out.write("' size=\"20\" maxlength=\"20\"/>\r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("	</table>\r\n");
}
      out.write("\r\n");
      out.write("<p><img src=\"images/dots.gif\" align=\"middle\" width=\"100%\"/></p>\r\n");
      out.write("	<table border=\"0\" cellpadding=\"0\" class=\"labels\" cellspacing=\"0\" width=\"100%\">\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td colspan=\"5\">\r\n");
      out.write("				<p><b><font size=\"4\"><span style=\"color: black; font-family: Verdana; font-size: 14pt; font-style: normal; font-weight: bold\">Configure\r\n");
      out.write("					Transactions to Start</span></font><font size=\"4\"></font></b></p>\r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>	\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td>\r\n");
      out.write("				<p><input type=\"submit\" name=\"submit\" value=\"Submit\" class=\"labels\"/></p>\r\n");
      out.write("			</td>\r\n");
      out.write("			<td align=\"right\"  class=\"labels\">\r\n");
      out.write("				<input type=\"checkbox\" name=\"Refresh\" value=\"Refresh\" ");
      out.print( (ConfigContext.getRefresh()>0L)?"checked":"");
      out.write("/>Auto-Refresh\r\n");
      out.write("			</td>\r\n");
      out.write("			<td align=\"right\"  class=\"labels\">\r\n");
      out.write("				<select name=\"AfterEnd\" size=\"1\">");
String sel = ConfigContext.isToStartAfterEnding()?"START":"STOP";
      out.write("\r\n");
      out.write("					<option ");
      out.print( sel.equals("START")?"selected=\"selected\"":"");
      out.write(" value=\"Start\">Start</option>\r\n");
      out.write("					<option ");
      out.print( sel.equals("STOP")?"selected=\"selected\"":"");
      out.write("value=\"Stop\">Stop</option>\r\n");
      out.write("				</select> after ending\r\n");
      out.write("			</td>\r\n");
      out.write("			<td align=\"right\"  class=\"labels\">\r\n");
      out.write("				<input type=\"checkbox\" name=\"Lock All\" value=\"Lock All\" ");
      out.print( ConfigContext.isLockAll()?"checked":"");
      out.write("/>Lock All\r\n");
      out.write("			</td>");
if(ConfigContext.isHosted() && (ConfigContext.getLoggedUserType()=='S') && (!ConfigContext.isSupportLoggedIn())){ 
      out.write("\r\n");
      out.write("			<td align=\"right\"  class=\"labels\">\r\n");
      out.write("				<input type=\"checkbox\" name=\"SU Lock All\" value=\"SU Lock All\" ");
      out.print( ConfigContext.isSuLockAll()?"checked":"");
      out.write("/>SU Lock All\r\n");
      out.write("			</td>");
}
      out.write("\r\n");
      out.write("			<td align=\"right\">\r\n");
      out.write("				<a href='");
      out.print( "ViewLog.jsp?IsAdmin=" + "true");
      out.write("'	class=\"labels\" target=\"_blank\">View Log</a>\r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("	</table>\r\n");
      out.write("	<table border=\"1\" cellpadding=\"0\" width=\"100%\" cellspacing=\"0\">\r\n");
      out.write("		<tr class=\"tablelabels\">\r\n");
      out.write("			<td>Transaction Flow Id</td>\r\n");
      out.write("			<td>Start Transaction Name</td>\r\n");
      out.write("			<td>Start/Stop</td>\r\n");
      out.write("			<td>State</td>\r\n");
      out.write("			<td>Scheduled</td>\r\n");
      out.write("			<td>Single Run</td>\r\n");
      out.write("			<td>Interval</td>\r\n");
      out.write("			<td>Shift</td>\r\n");
      out.write("			<td>Query Starts</td>\r\n");
      out.write("			<td>Counter</td>\r\n");
      out.write("			<td>Runs</td>\r\n");
      out.write("			");
if(ConfigContext.isHosted()){
      out.write("\r\n");
      out.write("			<td>Log Level</td>\r\n");
      out.write("			<td>Profile</td>\r\n");
      out.write("			<td>Kill</td>\r\n");
      out.write("			");
}
      out.write("\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr class=\"tablelabels\"><td colspan=");
      out.print( (ConfigContext.isHosted()?"14":"11"));
      out.write(">Scheduled Transaction Flows</td></tr>\r\n");
      out.write("		");

		Vector<TransactionContext> vTC = (ConfigContext.getLoggedUserType()=='V')?ConfigContext.sortByProfile():ConfigContext.getTransactionList();
		for(int i = 0; i< vTC.size(); i++){
		TransactionContext tc = (TransactionContext)(vTC.get(i)); 
		String tid = tc.getTransactionId();
		boolean stf = tc.isStateful();
		if(stf){
		Hashtable att = tc.getTransactionThreads();
		Iterator katt = att.keySet().iterator();
		while(katt.hasNext()){
		String profileName = (String)(katt.next());
		TransactionThread tt = (TransactionThread)(att.get(profileName));
		if((tt.getLogLevel()==-1111) && (ConfigContext.getLoggedUserType()=='V')){
			continue;
			}
		long ctm = System.currentTimeMillis();
		tt.setSubmitFlag(ctm);
		String state = ConfigContext.getProfileTransactionState(tc, profileName);
		String command = ConfigContext.getProfileTransactionCommand(tc, profileName);
		long trInt = tt.getTransactionInterval();
		long trShift = tt.getTransactionShiftFromHartBeat();
		int trLogLevel = tt.getLogLevel();
		String trShiftS = String.valueOf(trShift);
		String trIntS = String.valueOf(trInt);
		if(trShift<0L){
			trShiftS = "T";
			long hr = trInt / (60L * 60L);
			long mn = (trInt - hr * 60L * 60L) / 60L;
			long sc = trInt - hr * 60L * 60L - mn * 60L;
			trIntS = String.format("%1$02d", hr) + ":" + 
			         String.format("%1$02d", mn) + ":" + 
			         String.format("%1$02d", sc);
		}
		String trQST = tt.getTransactionStartTime().toString();
		String sfr = tt.getSuccesses() + "/" + tt.getFailures();
		int trCnt = tt.getTransactionCounter();
		boolean running = tt.isActive();
		boolean executing = tt.isExecuting();
		boolean runningEx = running || executing;
		boolean restoreRunning = tt.isRestoredRunning();
		tt.setRestoredRunning(false);
		
      out.write("\r\n");
      out.write("		<tr bgcolor=");
      out.print(running?(executing?"deeppink":"aqua"):(executing?"yellow":((trLogLevel==-1111)?"lightgrey":"white")));
      out.write(">\r\n");
      out.write("			<td><span class=\"tableitalic\"><a href='");
      out.print( "FlowProperties.jsp?CurrentFlowId=" + tid + "&CurrentProfile=" + profileName + "&IsAdmin=true" + "&IsFlow=1&WhoAmI=A" + brandSol);
      out.write("' target=\"data\">");
      out.print( tid);
      out.write("</a></span></td>\r\n");
      out.write("			<td><span class=\"table\">");
      out.print( tc.getParameters().get("tranname").getParameterValue());
      out.write("</span></td>\r\n");
      out.write("			<td>\r\n");
      out.write("				<span class=\"table\">\r\n");
      out.write("				<input type=\"checkbox\" name='");
      out.print( "TS:" + i + "=" + profileName);
      out.write('\'');
      out.write(' ');
      out.print( restoreRunning?"checked":"");
      out.write(" value=\"");
      out.print( ctm);
      out.write('"');
      out.write('/');
      out.write('>');
      out.print( command);
      out.write("\r\n");
      out.write("				</span>\r\n");
      out.write("			</td>\r\n");
      out.write("			<td><span class=\"table\">");
      out.print( state);
      out.write("</span></td>\r\n");
      out.write("			<td>\r\n");
      out.write("				<span class=\"table\">\r\n");
      out.write("				<input type=\"radio\" name='");
      out.print( "MS:" + i + "=" + profileName);
      out.write("' value=\"1\" ");
      out.print( (trInt>0L || trShift<0L)?"checked":"");
      out.write(' ');
      out.print( (runningEx || (trInt==0L && trShift>=0L))?"disabled":"");
      out.write(" />\r\n");
      out.write("				</span></td>\r\n");
      out.write("			<td>\r\n");
      out.write("				<span class=\"table\">\r\n");
      out.write("				<input type=\"radio\" name='");
      out.print( "MS:" + i + "=" + profileName);
      out.write("' value=\"0\" ");
      out.print( (trInt<=0L && trShift>=0L)?"checked":"");
      out.write(' ');
      out.print( (runningEx || (trInt==0L && trShift>=0L))?"disabled":"");
      out.write(" />\r\n");
      out.write("				</span></td>\r\n");
      out.write("			<td>\r\n");
      out.write("				<input type=\"text\" name='");
      out.print( "IN:" + i + "=" + profileName);
      out.write("' value='");
      out.print( trIntS);
      out.write("' maxlength=\"11\" class=\"table\" ");
      out.print( (runningEx || (trInt<=0L && trShift>=0L))?"disabled":"");
      out.write(" size=\"11\"/>\r\n");
      out.write("			</td>\r\n");
      out.write("			<td>\r\n");
      out.write("				<input type=\"text\" name='");
      out.print( "SH:" + i + "=" + profileName);
      out.write("' value='");
      out.print( trShiftS);
      out.write("' maxlength=\"11\" class=\"table\" ");
      out.print( runningEx?"disabled":"");
      out.write(" size=\"11\"/>\r\n");
      out.write("			</td>\r\n");
      out.write("			<td>\r\n");
      out.write("				<input type=\"text\" name='");
      out.print( "QS:" + i + "=" + profileName);
      out.write("' maxlength=\"22\" value='");
      out.print( trQST);
      out.write("' class=\"table\" ");
      out.print( runningEx?"disabled":"");
      out.write("/>\r\n");
      out.write("			</td>\r\n");
      out.write("			<td><span class=\"table\">\r\n");
      out.write("				<input type=\"text\" name='");
      out.print( "TC:" + i + "=" + profileName);
      out.write("' maxlength=\"11\" value='");
      out.print( trCnt);
      out.write("' class=\"table\" ");
      out.print( runningEx?"disabled":"");
      out.write(" size=\"11\"/>\r\n");
      out.write("				</span></td>\r\n");
      out.write("			<td><span class=\"table\"><a href='");
      out.print( "Logging.jsp?TCURL=" + tc.getPrimaryTSURL4Log(tt.getMode(), tt.getModec(), tt.getPrimaryDedicatedURL(), tt.getPrimaryDedicatedURLc()) + "&__LOG_QUERY_ID__=" + tid + "&CurrentProfile=" + profileName + brandSol);
      out.write("' target=\"_blank\">");
      out.print( sfr);
      out.write("</a></span></td>\r\n");
      out.write("			");
if(ConfigContext.isHosted()){
      out.write("\r\n");
      out.write("			<td>\r\n");
      out.write("				<input type=\"text\" name='");
      out.print( "LL:" + i + "=" + profileName);
      out.write("' value='");
      out.print( trLogLevel);
      out.write("' maxlength=\"5\" class=\"table\" size=\"5\"/>\r\n");
      out.write("			</td>\r\n");
      out.write("			<td><span class=\"table\">");
      out.print( profileName);
      out.write("</span></td>\r\n");
      out.write("			<td>\r\n");
      out.write("				<span class=\"table\">\r\n");
      out.write("				<input type=\"checkbox\" name='");
      out.print( "KL:" + i + "=" + profileName);
      out.write("'/>\r\n");
      out.write("				</span>\r\n");
      out.write("			</td>\r\n");
      out.write("			");
 }
      out.write("\r\n");
      out.write("		</tr>\r\n");
      out.write("		");
 }}}
		if(ConfigContext.getLoggedUserType()!='V'){
      out.write("\r\n");
      out.write("		<tr class=\"tablelabels\"><td colspan=");
      out.print( (ConfigContext.isHosted()?"14":"11"));
      out.write(">Utility Transaction Flows</td></tr>\r\n");
      out.write("		");

		for(int i = 0; i< ConfigContext.getTransactionList().size(); i++){
		TransactionContext tc = (TransactionContext)(ConfigContext.getTransactionList().get(i)); 
		String tid = tc.getTransactionId();
		boolean stf = tc.isStateful();
		if(!stf){
		Hashtable att = tc.getTransactionThreads();
		Iterator katt = att.keySet().iterator();
		while(katt.hasNext()){
		String profileName = (String)(katt.next());
		TransactionThread tt = (TransactionThread)(att.get(profileName));
		long ctm = System.currentTimeMillis();
		tt.setSubmitFlag(ctm);
		String state = ConfigContext.getProfileTransactionState(tc, profileName);
		String command = ConfigContext.getProfileTransactionCommand(tc, profileName);
		long trInt = tt.getTransactionInterval();
		long trShift = tt.getTransactionShiftFromHartBeat();
		int trLogLevel = tt.getLogLevel();
		String trShiftS = String.valueOf(trShift);
		String trIntS = String.valueOf(trInt);
		if(trShift<0L){
			trShiftS = "T";
			long hr = trInt / (60L * 60L);
			long mn = (trInt - hr * 60L * 60L) / 60L;
			long sc = trInt - hr * 60L * 60L - mn * 60L;
			trIntS = String.format("%1$02d", hr) + ":" + 
			         String.format("%1$02d", mn) + ":" + 
			         String.format("%1$02d", sc);
		}
		String trQST = tt.getTransactionStartTime().toString();
		String sfr = tt.getSuccesses() + "/" + tt.getFailures();
		int trCnt = tt.getTransactionCounter();
		boolean running = tt.isActive();
		boolean executing = tt.isExecuting();
		boolean runningEx = running || executing;
		boolean restoreRunning = tt.isRestoredRunning();
		tt.setRestoredRunning(false);
		
      out.write("\r\n");
      out.write("		<tr bgcolor=");
      out.print(running?(executing?"deeppink":"aqua"):(executing?"yellow":"white"));
      out.write(">\r\n");
      out.write("			<td><span class=\"table\"><a href='");
      out.print( "FlowProperties.jsp?CurrentFlowId=" + tid + "&CurrentProfile=" + profileName + "&IsAdmin=true" + "&IsFlow=1&WhoAmI=A" + brandSol);
      out.write("' target=\"data\">");
      out.print( tid);
      out.write("</a></span></td>\r\n");
      out.write("			<td><span class=\"table\">");
      out.print( tc.getParameters().get("tranname").getParameterValue());
      out.write("</span></td>\r\n");
      out.write("			<td>\r\n");
      out.write("				<span class=\"table\">\r\n");
      out.write("				<input type=\"checkbox\" name='");
      out.print( "TS:" + i + "=" + profileName);
      out.write('\'');
      out.write(' ');
      out.print( restoreRunning?"checked":"");
      out.write(" value=\"");
      out.print( ctm);
      out.write('"');
      out.write('/');
      out.write('>');
      out.print( command);
      out.write("\r\n");
      out.write("				</span>\r\n");
      out.write("			</td>\r\n");
      out.write("			<td><span class=\"table\">");
      out.print( state);
      out.write("</span></td>\r\n");
      out.write("			<td>\r\n");
      out.write("				<span class=\"table\">\r\n");
      out.write("				<input type=\"radio\" name='");
      out.print( "MS:" + i + "=" + profileName);
      out.write("' value=\"1\" ");
      out.print( (trInt>0L || trShift<0L)?"checked":"");
      out.write(' ');
      out.print( (runningEx || (trInt==0L && trShift>=0L))?"disabled":"");
      out.write(" />\r\n");
      out.write("				</span></td>\r\n");
      out.write("			<td>\r\n");
      out.write("				<span class=\"table\">\r\n");
      out.write("				<input type=\"radio\" name='");
      out.print( "MS:" + i + "=" + profileName);
      out.write("' value=\"0\" ");
      out.print( (trInt<=0L && trShift>=0L)?"checked":"");
      out.write(' ');
      out.print( (runningEx || (trInt==0L && trShift>=0L))?"disabled":"");
      out.write(" />\r\n");
      out.write("				</span></td>\r\n");
      out.write("			<td>\r\n");
      out.write("				<input type=\"text\" name='");
      out.print( "IN:" + i + "=" + profileName);
      out.write("' value='");
      out.print( trIntS);
      out.write("' maxlength=\"11\" class=\"table\" ");
      out.print( (runningEx || (trInt<=0L && trShift>=0L))?"disabled":"");
      out.write(" size=\"11\"/>\r\n");
      out.write("			</td>\r\n");
      out.write("			<td>\r\n");
      out.write("				<input type=\"text\" name='");
      out.print( "SH:" + i + "=" + profileName);
      out.write("' value='");
      out.print( trShiftS);
      out.write("' maxlength=\"11\" class=\"table\" ");
      out.print( runningEx?"disabled":"");
      out.write(" size=\"11\"/>\r\n");
      out.write("			</td>\r\n");
      out.write("			<td>\r\n");
      out.write("				<input type=\"text\" name='");
      out.print( "QS:" + i + "=" + profileName);
      out.write("' maxlength=\"22\" value='");
      out.print( trQST);
      out.write("' class=\"table\" ");
      out.print( runningEx?"disabled":"");
      out.write("/>\r\n");
      out.write("			</td>\r\n");
      out.write("			<td><span class=\"table\">\r\n");
      out.write("				<input type=\"text\" name='");
      out.print( "TC:" + i + "=" + profileName);
      out.write("' maxlength=\"11\" value='");
      out.print( trCnt);
      out.write("' class=\"table\" ");
      out.print( runningEx?"disabled":"");
      out.write(" size=\"11\"/>\r\n");
      out.write("				</span></td>\r\n");
      out.write("			<td><span class=\"table\"><a href='");
      out.print( "Logging.jsp?TCURL=" + tc.getPrimaryTSURL4Log(tt.getMode(), tt.getModec(), tt.getPrimaryDedicatedURL(), tt.getPrimaryDedicatedURLc()) + "&__LOG_QUERY_ID__=" + tid + "&CurrentProfile=" + profileName + brandSol);
      out.write("' target=\"_blank\">");
      out.print( sfr);
      out.write("</a></span></td>\r\n");
      out.write("			");
if(ConfigContext.isHosted()){
      out.write("\r\n");
      out.write("			<td>\r\n");
      out.write("				<input type=\"text\" name='");
      out.print( "LL:" + i + "=" + profileName);
      out.write("' value='");
      out.print( trLogLevel);
      out.write("' maxlength=\"5\" class=\"table\" size=\"5\"/>\r\n");
      out.write("			</td>\r\n");
      out.write("			<td><span class=\"table\">");
      out.print( profileName);
      out.write("</span></td>\r\n");
      out.write("			<td>\r\n");
      out.write("				<span class=\"table\">\r\n");
      out.write("				<input type=\"checkbox\" name='");
      out.print( "KL:" + i + "=" + profileName);
      out.write("'/>\r\n");
      out.write("				</span>\r\n");
      out.write("			</td>\r\n");
      out.write("			");
 }
      out.write("\r\n");
      out.write("		</tr>\r\n");
      out.write("		");
}}}}
      out.write("		\r\n");
      out.write("	</table>\r\n");
      out.write("	\r\n");
      out.write("<p>\r\n");
      out.write("	<input type=\"submit\" name=\"submit\" value=\"Submit\" class=\"labels\"/>\r\n");
      out.write("	</p>\r\n");
      out.write("</form>\r\n");
      out.write("<table border=\"0\" cellpadding=\"0\" width=\"100%\" cellspacing=\"0\">\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td><img src=\"images/dots.gif\" align=\"left\" width=\"100%\"/></td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td>\r\n");
      out.write("			<table border=\"1\" cellpadding=\"0\" width=\"100%\" cellspacing=\"0\">\r\n");
      out.write("				<tr class=\"tablelabels\">\r\n");
      out.write("					<td>Query Id</td>\r\n");
      out.write("					<td>Start Transaction Name</td>\r\n");
      out.write("					<td>Execute Query</td>\r\n");
      out.write("					");
if(ConfigContext.isHosted()){
      out.write("\r\n");
      out.write("					<td>Profile</td>\r\n");
      out.write("					<td>Kill</td>\r\n");
      out.write("					");
 }
      out.write("\r\n");
      out.write("				</tr>\r\n");
      out.write("				");
for(int i=0; i<ConfigContext.getQueryList().size(); i++){
			QueryContext qc = (QueryContext)(ConfigContext.getQueryList().get(i)); 
			String qid = qc.getTransactionId();
			Hashtable att = qc.getQueryInstances();
		Iterator katt = att.keySet().iterator();
		while(katt.hasNext()){
		String profileName = (String)(katt.next());
			TransactionBase tb = (TransactionBase)(att.get(profileName));
      out.write("\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td><span class=\"table\"><a href='");
      out.print( "FlowProperties.jsp?CurrentFlowId=" + qid + "&CurrentProfile=" + profileName + "&IsAdmin=true" + "&IsFlow=0&WhoAmI=A" + brandSol);
      out.write("' target=\"data\">");
      out.print( qid);
      out.write("</a></span></td>\r\n");
      out.write("					<td><span class=\"table\">");
      out.print( tb.getParameters().get("tranname").getParameterValue());
      out.write("</span></td>\r\n");
      out.write("					<td>\r\n");
      out.write("						<span class=\"table\"><a href=\"");
      out.print( qc.getHTTPGetQuery(profileName) + brandSol1);
      out.write("\" target=\"data\">GO</a></span>\r\n");
      out.write("					</td>\r\n");
      out.write("			");
if(ConfigContext.isHosted()){
      out.write("\r\n");
      out.write("			<td><span class=\"table\">");
      out.print( profileName);
      out.write("</span></td>\r\n");
      out.write("			<td><span class=\"table\"><a href='");
      out.print( "ProductDemoServlet?KilledProfile=" + profileName + "&KilledFlowId=" + qid + brandSol);
      out.write("'>KILL</a></span></td>\r\n");
      out.write("			");
 }
      out.write("\r\n");
      out.write("				</tr>\r\n");
      out.write("		");
 }}
      out.write("\r\n");
      out.write("			</table>			\r\n");
      out.write("		</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("</table>\r\n");
      out.write("<br/>\r\n");
      out.write("<br/>\r\n");
}else{
String em = "Your session has been lost. Please refresh your browser. If error persists please click Reset button below.";
if(refreshValue==null){
em = "Your session has been lost(authentication failed: null). Please refresh your browser. If error persists please click Reset button below.";
} else if(ConfigContext.getRefresh()==0L){
em = "Your session has been lost(authentication failed: 0). Please refresh your browser. If error persists please click Reset button below.";
} else if (ConfigContext.getRefresh()!=Long.valueOf(refreshValue)){
em = "Your session has been lost(authentication failed). Please refresh your browser. If error persists please click Reset button below.";
}
      out.write('\r');
      out.write('\n');
      if (true) {
        _jspx_page_context.forward("/ErrorMessage.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("ErrorMessageText", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf( em), request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("ErrorMessageReturn", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("IWLogin.jsp", request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("PortalBrand", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf( brand), request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("PortalSolutions", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf( solutions), request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("ButtonLable", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("Reset", request.getCharacterEncoding()));
        return;
      }
      out.write('\r');
      out.write('\n');
}
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
