/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.83
 * Generated at: 2025-12-04 23:04:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.interweave.businessDaemon.*;
import java.util.*;

public final class BDMinitor_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("com.interweave.businessDaemon");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

String brand = request.getParameter("PortalBrand");
if(brand==null){
brand="";
}
String solutions = request.getParameter("PortalSolutions");
if(solutions==null){
solutions="";
}
response.setHeader("Cache-Control","no-cache"); //HTTP 1.1
response.setHeader("Pragma","no-cache"); //HTTP 1.0
response.setDateHeader ("Expires", -1);

      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>IM Monitor Page</title>\r\n");
      out.write("<style>\r\n");
      out.write("<!--\r\n");
      out.write(".labels\r\n");
      out.write("   {\r\n");
      out.write("   color: black; font-family: Verdana; font-size: 7pt; font-style: normal; font-weight: bold;\r\n");
      out.write("   }\r\n");
      out.write(".tablelabels\r\n");
      out.write("   {\r\n");
      out.write("   color: black; font-family: Verdana; font-size: 6pt; font-style: normal; font-weight: bold;\r\n");
      out.write("   }\r\n");
      out.write(".table\r\n");
      out.write("   {\r\n");
      out.write("   color: black; font-family: Verdana; font-size: 6pt; font-style: normal; font-weight: bold;\r\n");
      out.write("   }\r\n");
      out.write("-->\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<table border=\"0\" cellpadding=\"0\" width=\"100%\" cellspacing=\"0\">\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td><img src=\"");
      out.print( "images" + ((brand==null || brand.equals(""))?"":("/" + brand)) + "/IT Banner.png");
      out.write("\" alt=\"Title\" align=\"left\" width=\"100%\" height=\"94\"/></td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td><span style=\"color: black; font-family: Verdana; font-size: 15pt; font-style: normal; font-weight: bold\">InterWeave Monitoring Utility</span><br/></td>\r\n");
      out.write("	</tr>\r\n");
      out.write("</table>\r\n");
 String currentProfileName = request.getParameter("CurrentProfile");
String email = null;
if(currentProfileName!=null){
int pzc = currentProfileName.lastIndexOf(":");
if(pzc>0){
email = currentProfileName.substring(pzc).trim();
}}
long rfInt = ConfigContext.getRefreshInterval();

      out.write("\r\n");
      out.write("<applet height=\"0\" width=\"0\" code=\"TransState2.class\" name=\"AP20\">\r\n");
      out.write("	<param name=\"ProfileName\" value='");
      out.print( ((currentProfileName==null)?"__default_profile__":currentProfileName));
      out.write("'/>\r\n");
      out.write("	<param name=\"RefreshInterval\" value='");
      out.print( rfInt);
      out.write("'/>\r\n");
      out.write("</applet>\r\n");
      out.write("<p><b><font size=\"4\"><span style=\"color: black; font-family: Verdana; font-size: 14pt; font-style: normal; font-weight: bold\">Running Transaction Flows</span></font></b></p>\r\n");
      out.write("	<table border=\"1\" cellpadding=\"0\" width=\"100%\" cellspacing=\"0\">\r\n");
      out.write("		<tr class=\"tablelabels\">\r\n");
      out.write("			<td>Transaction Flow Id</td>\r\n");
      out.write("			<td>State</td>\r\n");
      out.write("			<td>Scheduled</td>\r\n");
      out.write("			<td>Single Run</td>\r\n");
      out.write("			<td>Interval</td>\r\n");
      out.write("			<td>Shift</td>\r\n");
      out.write("			<td>Query Starts</td>\r\n");
      out.write("			<td>Counter</td>\r\n");
      out.write("			<td>Runs</td>\r\n");
      out.write("			");
if(ConfigContext.isHosted()&&(currentProfileName==null)){
      out.write("\r\n");
      out.write("			<td>Profile</td>\r\n");
      out.write("			");
 }
      out.write("\r\n");
      out.write("		</tr>\r\n");
		for(int i = 0; i< ConfigContext.getTransactionList().size(); i++){
		TransactionContext tc = (TransactionContext)(ConfigContext.getTransactionList().get(i)); 
		String tid = tc.getTransactionId();
		Hashtable att = tc.getTransactionThreads();
		Iterator katt = att.keySet().iterator();
		while(katt.hasNext()){
		String profileName = (String)(katt.next());
		if(currentProfileName!=null && ((email==null) || (!profileName.endsWith(email)))){
			continue;
			}
		TransactionThread tt = (TransactionThread)(att.get(profileName));
		boolean stopped = !(tt.isActive() || tt.isExecuting());
		long trInt = tt.getTransactionInterval();
		long trShift = tt.getTransactionShiftFromHartBeat();
		String trShiftS = String.valueOf(trShift);
		String trIntS = String.valueOf(trInt);
		if(trShift<0L){
			trShiftS = "T";
			long hr = trInt / (60L * 60L);
			long mn = (trInt - hr * 60L * 60L) / 60L;
			long sc = trInt - hr * 60L * 60L - mn * 60L;
			trIntS = String.format("%1$02d", hr) + ":" + 
			         String.format("%1$02d", mn) + ":" + 
			         String.format("%1$02d", sc);
		}
		String state = "STOPPED";
		String trQST = "";
		String sfr = "0/0";
		int trCnt = 0;
		if(stopped){
		trQST = tt.getTransactionStartTime().toString();
		sfr = tt.getSuccesses() + "/" + tt.getFailures();
		trCnt = tt.getTransactionCounter();
		}
		if(!stopped){
      out.write("<applet height=\"0\" width=\"0\" code=\"TransState0.class\" name='");
      out.print( "AP00:" + i + "=" + profileName);
      out.write("'>\r\n");
      out.write("					<param name=\"Index\" value='");
      out.print( "" + i);
      out.write("'/>\r\n");
      out.write("					<param name=\"ProfileName\" value='");
      out.print( profileName);
      out.write("'/>\r\n");
      out.write("					<param name=\"RefreshInterval\" value='");
      out.print( rfInt);
      out.write("'/>\r\n");
      out.write("				</applet>");
}
      out.write("\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td><span class=\"table\"><a href='");
      out.print( "FlowProperties.jsp?FromMonitor=1&CurrentFlowId=" + tid + "&CurrentProfile=" + profileName + "&IsFlow=1");
      out.write("' target=\"_blank\">");
      out.print( tid);
      out.write("</a></span></td>\r\n");
      out.write("			<td><span class=\"table\">");
if(stopped){
      out.print( state);
}else{
      out.write(" \r\n");
      out.write("				<applet height=\"20\" width=\"70\" code=\"TransState1.class\" class=\"table\" name='");
      out.print( "AP10:" + i + "=" + profileName);
      out.write("'>\r\n");
      out.write("<!--					<param name=\"Index\" value='");
      out.print( "" + i);
      out.write("'/>\r\n");
      out.write("					<param name=\"Mode\" value=\"0\"/>\r\n");
      out.write("					<param name=\"ProfileName\" value='");
      out.print( profileName);
      out.write("'/>\r\n");
      out.write("					<param name=\"RefreshInterval\" value='");
      out.print( rfInt);
      out.write("'/>-->\r\n");
      out.write("				</applet>");
}
      out.write("</span>\r\n");
      out.write("			</td>\r\n");
      out.write("			<td>\r\n");
      out.write("				<span class=\"table\">\r\n");
      out.write("				<input type=\"radio\" name='");
      out.print( "MS:" + i + "=" + profileName);
      out.write("' value=\"1\" ");
      out.print( (trInt>0L || trShift<0L)?"checked":"");
      out.write(" \"disabled\" />\r\n");
      out.write("				</span></td>\r\n");
      out.write("			<td>\r\n");
      out.write("				<span class=\"table\">\r\n");
      out.write("				<input type=\"radio\" name='");
      out.print( "MS:" + i + "=" + profileName);
      out.write("' value=\"0\" ");
      out.print( (trInt<=0L && trShift>=0L)?"checked":"");
      out.write(" \"disabled\" />\r\n");
      out.write("				</span></td>\r\n");
      out.write("			<td><span class=\"table\">");
      out.print( trIntS);
      out.write("</span></td>\r\n");
      out.write("			<td><span class=\"table\">");
      out.print( trShiftS);
      out.write("</span></td>\r\n");
      out.write("			<td><span class=\"table\">");
if(stopped){
      out.print( trQST);
}else{
      out.write("\r\n");
      out.write("				<applet height=\"20\" width=\"140\" code=\"TransState1.class\" class=\"table\" name='");
      out.print( "AP11:" + i + "=" + profileName);
      out.write("'>\r\n");
      out.write("<!--					<param name=\"Index\" value='");
      out.print( "" + i);
      out.write("'/>\r\n");
      out.write("					<param name=\"Mode\" value=\"1\"/>\r\n");
      out.write("					<param name=\"ProfileName\" value='");
      out.print( profileName);
      out.write("'/>\r\n");
      out.write("					<param name=\"RefreshInterval\" value='");
      out.print( rfInt);
      out.write("'/>-->\r\n");
      out.write("				</applet>");
}
      out.write("</span>\r\n");
      out.write("			</td>\r\n");
      out.write("			<td><span class=\"table\">");
if(stopped){
      out.print( trCnt);
}else{
      out.write("\r\n");
      out.write("				<applet height=\"20\" width=\"40\" code=\"TransState1.class\" class=\"table\" name='");
      out.print( "AP12:" + i + "=" + profileName);
      out.write("'>\r\n");
      out.write("<!--					<param name=\"Index\" value='");
      out.print( "" + i);
      out.write("'/>\r\n");
      out.write("					<param name=\"Mode\" value=\"2\"/>\r\n");
      out.write("					<param name=\"ProfileName\" value='");
      out.print( profileName);
      out.write("'/>\r\n");
      out.write("					<param name=\"RefreshInterval\" value='");
      out.print( rfInt);
      out.write("'/>-->\r\n");
      out.write("				</applet>");
}
      out.write("</span>\r\n");
      out.write("			</td>\r\n");
      out.write("			<td><span class=\"table\">");
if(stopped){
      out.print( sfr);
}else{
      out.write(" \r\n");
      out.write("				<applet height=\"20\" width=\"40\" code=\"TransState1.class\" class=\"table\" name='");
      out.print( "AP13:" + i + "=" + profileName);
      out.write("'>\r\n");
      out.write("<!--					<param name=\"Index\" value='");
      out.print( "" + i);
      out.write("'/>\r\n");
      out.write("					<param name=\"Mode\" value=\"3\"/>\r\n");
      out.write("					<param name=\"ProfileName\" value='");
      out.print( profileName);
      out.write("'/>\r\n");
      out.write("					<param name=\"RefreshInterval\" value='");
      out.print( rfInt);
      out.write("'/>-->\r\n");
      out.write("				</applet>");
}
      out.write("</span>\r\n");
      out.write("			</td>\r\n");
      out.write("			");
if(ConfigContext.isHosted()&&(currentProfileName==null)){
      out.write("\r\n");
      out.write("			<td><span class=\"table\">");
      out.print( profileName);
      out.write("</span></td>\r\n");
      out.write("			");
 }
      out.write("\r\n");
      out.write("		</tr>\r\n");
      out.write("		");
 }}
      out.write("\r\n");
      out.write("		\r\n");
      out.write("	</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("<HEAD> \r\n");
      out.write("<META HTTP-EQUIV=\"PRAGMA\" CONTENT=\"NO-CACHE\"> \r\n");
      out.write("</HEAD> \r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
