/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.83
 * Generated at: 2025-12-04 23:05:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.interweave.businessDaemon.*;
import java.util.*;

public final class EditCompanyProfile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("com.interweave.businessDaemon");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=iso-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

String brand = request.getParameter("PortalBrand");
if(brand==null){
brand="";
}
String solutions = request.getParameter("PortalSolutions");
if(solutions==null){
solutions="";
}
String brandSol = "";
if (brand != null && brand.length() > 0) {
	brandSol += "&PortalBrand=" + brand;
}
if (solutions != null && solutions.length() > 0) {
	brandSol += "&PortalSolutions=" + solutions;
}
String brandSol1 = "";
if (brand != null && brand.length() > 0) {
	brandSol1 += "?PortalBrand=" + brand;
}
if (solutions != null && solutions.length() > 0) {
	brandSol1 += ((brand != null && brand.length() > 0)?"&":"?") + "PortalSolutions=" + solutions;
} 
boolean li = ConfigContext.isUserLoggedIn();
ConfigContext.setUserLoggedIn(false);
String currentProfileName = request.getParameter("CurrentProfile");
String oldEmail = request.getParameter("Email");
if(oldEmail==null){
oldEmail = "";
}
String oldCompany = request.getParameter("Company");
if(oldCompany==null){
oldCompany = "";
}
String firstName = "";
String lastName = "";
String company = "";
String solution = "";
String email = "";
Hashtable att = null;
TransactionThread tt = null;
if(currentProfileName!=null){
att = ConfigContext.getRequestCompany().getTransactionThreads();
if(att!=null){
tt = (TransactionThread)(att.get(currentProfileName));
if(tt!=null){
firstName = tt.getFirstName();
lastName = tt.getLastName();
company = oldCompany;
solution = tt.getTitle();
email = oldEmail;
}
}
}

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("  <meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\" />\r\n");
      out.write("  <title>Company Registration Page</title><style>\r\n");
      out.write("<!--\r\n");
      out.write(".labels\r\n");
      out.write("   {\r\n");
      out.write("   color: black; font-family: Verdana; font-size: 12pt; font-style: normal; font-weight: bold;\r\n");
      out.write("   }\r\n");
      out.write(".table\r\n");
      out.write("   {\r\n");
      out.write("   color: black; font-family: Verdana; font-size: 10pt; font-style: normal; font-weight: normal;\r\n");
      out.write("   }\r\n");
      out.write("-->\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<table border=\"0\" cellpadding=\"5\" width=\"100%\">\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td colspan=\"3\"><img src=\"");
      out.print( "images" + ((brand==null || brand.equals(""))?"":("/" + brand)) + "/IT Banner.png");
      out.write("\" alt=\"Title\" align=\"left\" width=\"100%\" height=\"94\"/></td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td><span style=\"color: black; font-family: Verdana; font-size: 15pt; font-style: normal; font-weight: bold\">Edit\r\n");
      out.write("		Company Profile</span><br/></td><td align=\"right\"><a href='");
      out.print( "IWLogin.jsp" + brandSol1);
      out.write("' target=\"_top\" class=\"labels\">Logout</a></td><td align=\"right\"><a href='http://interweave.biz' class=\"labels\" target=\"_blank\">InterWeave</a></td>\r\n");
      out.write("	</tr>\r\n");
      out.write("</table>\r\n");
      out.write("<form action=\"EditCompanyProfileServlet\" method=\"post\">\r\n");
      out.write("<input type=\"hidden\" name=\"PortalBrand\" value=\"");
      out.print( brand);
      out.write("\"/>\r\n");
      out.write("<input type=\"hidden\" name=\"PortalSolutions\" value=\"");
      out.print( solutions);
      out.write("\"/>\r\n");
      out.write("\r\n");
      out.write("<table border=\"0\" cellpadding=\"5\" width=\"100%\" class=\"labels\">\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td width=\"25%\"><span class=\"table\">Company</span></td>\r\n");
      out.write("		<td>\r\n");
      out.write("			<span class=\"table\"><input type=\"text\" name=\"Company\" maxlength=\"255\" class=\"table\" value='");
      out.print( oldCompany);
      out.write('\'');
      out.write(' ');
      out.print( li?"disabled":"");
      out.write("/></span>\r\n");
      out.write("		</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td width=\"25%\"><span class=\"table\">Administrator's e-mail</span></td>\r\n");
      out.write("		<td>\r\n");
      out.write("			<span class=\"table\"><input type=\"text\" name=\"Email\" maxlength=\"255\" class=\"table\" value='");
      out.print( oldEmail);
      out.write('\'');
      out.write(' ');
      out.print( li?"disabled":"");
      out.write("/></span>\r\n");
      out.write("		</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td width=\"25%\"><span class=\"table\">Password</span></td>\r\n");
      out.write("		<td>\r\n");
      out.write("			<span class=\"table\"><input type=\"password\" name=\"Password\" maxlength=\"255\" class=\"table\" ");
      out.print( li?"disabled":"");
      out.write("/>\r\n");
      out.write("		</span></td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	\r\n");
      out.write("</table>\r\n");
      out.write("	<p>\r\n");
      out.write("		<input type=\"submit\" name=\"submit\" value=\"Load Company Profile\" class=\"labels\" ");
      out.print( li?"disabled":"");
      out.write("/>\r\n");
      out.write("	</p>\r\n");
      out.write("	</form>\r\n");
      out.write("<form action=\"SaveCompanyProfileServlet\" method=\"post\">\r\n");
      out.write("<input type=\"hidden\" name=\"OldProfile\" value='");
      out.print( currentProfileName);
      out.write("'/>\r\n");
      out.write("<input type=\"hidden\" name=\"Type\" value='");
      out.print( solution);
      out.write("'/>\r\n");
      out.write("<input type=\"hidden\" name=\"CompanyOrganization\" value='");
      out.print( company);
      out.write("'/>\r\n");
      out.write("<input type=\"hidden\" name=\"PortalBrand\" value=\"");
      out.print( brand);
      out.write("\"/>\r\n");
      out.write("<input type=\"hidden\" name=\"PortalSolutions\" value=\"");
      out.print( solutions);
      out.write("\"/>\r\n");
      out.write("<table border=\"0\" cellpadding=\"5\" width=\"100%\" class=\"labels\">\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td><span class=\"table\">Company/Organization</span></td>\r\n");
      out.write("		<td>\r\n");
      out.write("			<span class=\"table\">");
      out.print( company);
      out.write("</span></td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr align=\"left\" valign=\"middle\">\r\n");
      out.write("		<td width=\"25%\"><span class=\"table\">First Name</span></td>\r\n");
      out.write("		<td>\r\n");
      out.write("			<span class=\"table\"><input type=\"text\" name=\"FirstName\" maxlength=\"45\" class=\"table\" value='");
      out.print( firstName);
      out.write('\'');
      out.write(' ');
      out.print( (!li)?"disabled":"");
      out.write("/>\r\n");
      out.write("		</span></td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td><span class=\"table\">Last Name</span></td>\r\n");
      out.write("		<td>\r\n");
      out.write("			<span class=\"table\"><input type=\"text\" name=\"LastName\" maxlength=\"45\" class=\"table\" value='");
      out.print( lastName);
      out.write('\'');
      out.write(' ');
      out.print( (!li)?"disabled":"");
      out.write("/>\r\n");
      out.write("		</span></td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td><span class=\"table\">Administrator's e-mail</span></td>\r\n");
      out.write("		<td>\r\n");
      out.write("			<span class=\"table\"><input type=\"text\" name=\"Email\" maxlength=\"255\" class=\"table\" value='");
      out.print( email);
      out.write('\'');
      out.write(' ');
      out.print( (!li)?"disabled":"");
      out.write("/></span>\r\n");
      out.write("		</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td><span class=\"table\">Solution type</span></td>\r\n");
      out.write("		<td><span class=\"table\">");
      out.print( solution);
      out.write("</span></td>\r\n");
      out.write("	</tr>\r\n");
      out.write("</table>\r\n");
      out.write("	<p>\r\n");
      out.write("		<input type=\"submit\" name=\"submit\" value=\"Next\" class=\"labels\" ");
      out.print( (!li)?"disabled":"");
      out.write("/>\r\n");
      out.write("	</p>\r\n");
      out.write("	</form>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
