/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.83
 * Generated at: 2026-01-13 00:51:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import com.interweave.error.*;

public final class ErrorMessage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("com.interweave.error");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=iso-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

// Parse request parameters
String target = request.getParameter("ErrorMessageTarget");
String brand = request.getParameter("PortalBrand");
if(brand==null){
	brand="";
}
String button = request.getParameter("ButtonLable");
if(button==null || button.trim().length()==0){
	button="OK";
}
String solutions = request.getParameter("PortalSolutions");
if(solutions==null){
	solutions="";
}
String env2Con = request.getParameter("Env2Con");
if(env2Con==null){
	env2Con="COM";
}
String brandSol = "";
if (brand != null && brand.length() > 0) {
	brandSol += "?PortalBrand=" + brand;
}
if (solutions != null && solutions.length() > 0) {
	brandSol += ((brand != null && brand.length() > 0)?"&":"?") + "PortalSolutions=" + solutions;
}

// Parse error details - support both legacy text errors and new structured IWError
String errorText = request.getParameter("ErrorMessageText");
String errorCode = request.getParameter("ErrorCode");
String errorCause = request.getParameter("ErrorCause");
String errorComponent = request.getParameter("ErrorComponent");
String errorResolution = request.getParameter("ErrorResolution");
String errorDocLink = request.getParameter("ErrorDocLink");
String transactionId = request.getParameter("TransactionId");

// TEMPORARILY DISABLED: Error framework not compiled
// Try to get structured error from request attribute
// IWError iwError = null;
// try {
// 	iwError = (IWError) request.getAttribute("iwError");
// } catch (Exception e) {
// 	// Ignore if error classes not available - just use text error
// }

// Use structured error if available, otherwise fall back to parameters/text
// if (iwError != null) {
// 	if (errorText == null) errorText = iwError.getMessage();
// 	if (errorCode == null && iwError.getErrorCode() != null) errorCode = iwError.getErrorCode().getCode();
// 	if (errorCause == null) errorCause = iwError.getCause();
// 	if (errorComponent == null) errorComponent = iwError.getComponent();
// 	if (errorResolution == null) errorResolution = iwError.getResolution();
// 	if (errorDocLink == null) errorDocLink = iwError.getDocumentationLink();
// 	if (transactionId == null) transactionId = iwError.getTransactionId();
// }

// Ensure we have at least error text
if (errorText == null) {
	errorText = "An unexpected error occurred. Please contact support for assistance.";
}

// TEMPORARILY DISABLED: ErrorCode classes not compiled
// Try to lookup documentation if we have an error code but no resolution
// if (errorCode != null && errorResolution == null) {
// 	try {
// 		ErrorCode code = ErrorCode.findByCode(errorCode);
// 		if (code != null) {
// 			errorResolution = ErrorDocumentation.getResolutionSteps(code);
// 			if (errorDocLink == null) {
// 				errorDocLink = ErrorDocumentation.getDocumentationUrl(code);
// 			}
// 		}
// 	} catch (Exception e) {
// 		// Silently ignore - just won't have enhanced error info
// 	}
// }

// Generate transaction ID if not present
if (transactionId == null || transactionId.trim().length() == 0) {
	transactionId = "TXN-" + UUID.randomUUID().toString().substring(0, 8).toUpperCase();
}

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("  <meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\" />\r\n");
      out.write("  <title>Error - InterWeave IDE Portal</title>\r\n");
      out.write("  <style>\r\n");
      out.write("    body {\r\n");
      out.write("      font-family: Arial, Helvetica, sans-serif;\r\n");
      out.write("      margin: 0;\r\n");
      out.write("      padding: 0;\r\n");
      out.write("      background-color: #f5f5f5;\r\n");
      out.write("    }\r\n");
      out.write("    .header-banner {\r\n");
      out.write("      width: 100%;\r\n");
      out.write("      border-bottom: 2px solid #ddd;\r\n");
      out.write("    }\r\n");
      out.write("    .container {\r\n");
      out.write("      max-width: 900px;\r\n");
      out.write("      margin: 30px auto;\r\n");
      out.write("      padding: 0 20px;\r\n");
      out.write("    }\r\n");
      out.write("    .error-box {\r\n");
      out.write("      background-color: #ffffff;\r\n");
      out.write("      border: 2px solid #cc0000;\r\n");
      out.write("      border-radius: 8px;\r\n");
      out.write("      padding: 30px;\r\n");
      out.write("      box-shadow: 0 2px 8px rgba(0,0,0,0.1);\r\n");
      out.write("    }\r\n");
      out.write("    .error-header {\r\n");
      out.write("      display: flex;\r\n");
      out.write("      align-items: center;\r\n");
      out.write("      margin-bottom: 20px;\r\n");
      out.write("      padding-bottom: 15px;\r\n");
      out.write("      border-bottom: 1px solid #eee;\r\n");
      out.write("    }\r\n");
      out.write("    .error-icon {\r\n");
      out.write("      font-size: 48px;\r\n");
      out.write("      color: #cc0000;\r\n");
      out.write("      margin-right: 15px;\r\n");
      out.write("    }\r\n");
      out.write("    .error-title {\r\n");
      out.write("      flex: 1;\r\n");
      out.write("    }\r\n");
      out.write("    .error-title h1 {\r\n");
      out.write("      margin: 0;\r\n");
      out.write("      font-size: 24px;\r\n");
      out.write("      color: #cc0000;\r\n");
      out.write("      font-weight: bold;\r\n");
      out.write("    }\r\n");
      out.write("    .error-code {\r\n");
      out.write("      display: inline-block;\r\n");
      out.write("      background-color: #ffeeee;\r\n");
      out.write("      color: #cc0000;\r\n");
      out.write("      padding: 4px 12px;\r\n");
      out.write("      border-radius: 4px;\r\n");
      out.write("      font-size: 12px;\r\n");
      out.write("      font-weight: bold;\r\n");
      out.write("      font-family: 'Courier New', monospace;\r\n");
      out.write("      margin-top: 5px;\r\n");
      out.write("    }\r\n");
      out.write("    .error-section {\r\n");
      out.write("      margin: 20px 0;\r\n");
      out.write("      padding: 15px;\r\n");
      out.write("      background-color: #f9f9f9;\r\n");
      out.write("      border-left: 4px solid #cc0000;\r\n");
      out.write("      border-radius: 4px;\r\n");
      out.write("    }\r\n");
      out.write("    .error-section-title {\r\n");
      out.write("      font-weight: bold;\r\n");
      out.write("      font-size: 14px;\r\n");
      out.write("      color: #333;\r\n");
      out.write("      margin-bottom: 8px;\r\n");
      out.write("      text-transform: uppercase;\r\n");
      out.write("      letter-spacing: 0.5px;\r\n");
      out.write("    }\r\n");
      out.write("    .error-section-content {\r\n");
      out.write("      font-size: 13px;\r\n");
      out.write("      color: #555;\r\n");
      out.write("      line-height: 1.6;\r\n");
      out.write("    }\r\n");
      out.write("    .error-message {\r\n");
      out.write("      font-size: 15px;\r\n");
      out.write("      color: #333;\r\n");
      out.write("      line-height: 1.6;\r\n");
      out.write("      margin: 15px 0;\r\n");
      out.write("    }\r\n");
      out.write("    .resolution-steps {\r\n");
      out.write("      background-color: #eef7ff;\r\n");
      out.write("      border-left: 4px solid #0066cc;\r\n");
      out.write("      padding: 15px;\r\n");
      out.write("      margin: 20px 0;\r\n");
      out.write("      border-radius: 4px;\r\n");
      out.write("    }\r\n");
      out.write("    .resolution-steps .error-section-title {\r\n");
      out.write("      color: #0066cc;\r\n");
      out.write("      border-left-color: #0066cc;\r\n");
      out.write("    }\r\n");
      out.write("    .resolution-steps ul {\r\n");
      out.write("      margin: 10px 0;\r\n");
      out.write("      padding-left: 25px;\r\n");
      out.write("    }\r\n");
      out.write("    .resolution-steps li {\r\n");
      out.write("      margin: 8px 0;\r\n");
      out.write("      line-height: 1.5;\r\n");
      out.write("    }\r\n");
      out.write("    .transaction-id {\r\n");
      out.write("      font-family: 'Courier New', monospace;\r\n");
      out.write("      background-color: #f0f0f0;\r\n");
      out.write("      padding: 2px 6px;\r\n");
      out.write("      border-radius: 3px;\r\n");
      out.write("      font-size: 12px;\r\n");
      out.write("      color: #666;\r\n");
      out.write("    }\r\n");
      out.write("    .support-section {\r\n");
      out.write("      background-color: #fffbf0;\r\n");
      out.write("      border: 1px solid #ffd700;\r\n");
      out.write("      border-radius: 4px;\r\n");
      out.write("      padding: 15px;\r\n");
      out.write("      margin: 20px 0;\r\n");
      out.write("    }\r\n");
      out.write("    .support-section-title {\r\n");
      out.write("      font-weight: bold;\r\n");
      out.write("      font-size: 13px;\r\n");
      out.write("      color: #b8860b;\r\n");
      out.write("      margin-bottom: 8px;\r\n");
      out.write("    }\r\n");
      out.write("    .support-section-content {\r\n");
      out.write("      font-size: 12px;\r\n");
      out.write("      color: #666;\r\n");
      out.write("    }\r\n");
      out.write("    .doc-link {\r\n");
      out.write("      display: inline-block;\r\n");
      out.write("      background-color: #0066cc;\r\n");
      out.write("      color: #ffffff;\r\n");
      out.write("      text-decoration: none;\r\n");
      out.write("      padding: 8px 16px;\r\n");
      out.write("      border-radius: 4px;\r\n");
      out.write("      font-size: 13px;\r\n");
      out.write("      margin-top: 10px;\r\n");
      out.write("      transition: background-color 0.2s;\r\n");
      out.write("    }\r\n");
      out.write("    .doc-link:hover {\r\n");
      out.write("      background-color: #0052a3;\r\n");
      out.write("    }\r\n");
      out.write("    .button-container {\r\n");
      out.write("      margin-top: 30px;\r\n");
      out.write("      text-align: center;\r\n");
      out.write("    }\r\n");
      out.write("    .submit-button {\r\n");
      out.write("      background-color: #CCCCCC;\r\n");
      out.write("      border: 1px solid #000000;\r\n");
      out.write("      font-family: Verdana, Arial;\r\n");
      out.write("      font-size: 12px;\r\n");
      out.write("      font-weight: bold;\r\n");
      out.write("      padding: 8px 24px;\r\n");
      out.write("      cursor: pointer;\r\n");
      out.write("      border-radius: 4px;\r\n");
      out.write("      transition: background-color 0.2s;\r\n");
      out.write("    }\r\n");
      out.write("    .submit-button:hover {\r\n");
      out.write("      background-color: #BBBBBB;\r\n");
      out.write("    }\r\n");
      out.write("    .timestamp {\r\n");
      out.write("      font-size: 11px;\r\n");
      out.write("      color: #999;\r\n");
      out.write("      text-align: right;\r\n");
      out.write("      margin-top: 20px;\r\n");
      out.write("    }\r\n");
      out.write("  </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- Header Banner -->\r\n");
      out.write("<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" class=\"header-banner\">\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td><img src=\"");
      out.print( "images" + ((brand==null || brand.equals(""))?"":("/" + brand)) + "/IT Banner.png");
      out.write("\" alt=\"InterWeave IDE\" align=\"left\" width=\"100%\" height=\"94\"/></td>\r\n");
      out.write("	</tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("<!-- Error Content -->\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("	<div class=\"error-box\">\r\n");
      out.write("		<!-- Error Header -->\r\n");
      out.write("		<div class=\"error-header\">\r\n");
      out.write("			<div class=\"error-icon\">&#9888;</div>\r\n");
      out.write("			<div class=\"error-title\">\r\n");
      out.write("				<h1>Error Occurred</h1>\r\n");
      out.write("				");
 if (errorCode != null && errorCode.trim().length() > 0) { 
      out.write("\r\n");
      out.write("					<span class=\"error-code\">Error Code: ");
      out.print( errorCode );
      out.write("</span>\r\n");
      out.write("				");
 } 
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<!-- Error Message -->\r\n");
      out.write("		<div class=\"error-message\">\r\n");
      out.write("			");
      out.print( errorText );
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<!-- Error Details Sections -->\r\n");
      out.write("		");
 if (errorComponent != null && errorComponent.trim().length() > 0) { 
      out.write("\r\n");
      out.write("		<div class=\"error-section\">\r\n");
      out.write("			<div class=\"error-section-title\">Affected Component</div>\r\n");
      out.write("			<div class=\"error-section-content\">");
      out.print( errorComponent );
      out.write("</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("		");
 if (errorCause != null && errorCause.trim().length() > 0) { 
      out.write("\r\n");
      out.write("		<div class=\"error-section\">\r\n");
      out.write("			<div class=\"error-section-title\">Cause</div>\r\n");
      out.write("			<div class=\"error-section-content\">");
      out.print( errorCause );
      out.write("</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<!-- Resolution Steps -->\r\n");
      out.write("		");
 if (errorResolution != null && errorResolution.trim().length() > 0) { 
      out.write("\r\n");
      out.write("		<div class=\"resolution-steps\">\r\n");
      out.write("			<div class=\"error-section-title\">&#128161; How to Resolve</div>\r\n");
      out.write("			<div class=\"error-section-content\">\r\n");
      out.write("				");

				// Format resolution steps - convert line breaks to list items if needed
				String formattedResolution = errorResolution;
				if (errorResolution.contains("\n") && !errorResolution.contains("<")) {
					// Plain text with line breaks - convert to list
					String[] steps = errorResolution.split("\n");
					out.println("<ul>");
					for (String step : steps) {
						if (step.trim().length() > 0) {
							// Remove leading numbers/bullets if present
							String cleanStep = step.trim().replaceAll("^[0-9]+\\.\\s*", "").replaceAll("^[-*]\\s*", "");
							out.println("<li>" + cleanStep + "</li>");
						}
					}
					out.println("</ul>");
				} else {
					// Already formatted or single line
					out.println(formattedResolution);
				}
				
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<!-- Documentation Link -->\r\n");
      out.write("		");
 if (errorDocLink != null && errorDocLink.trim().length() > 0) { 
      out.write("\r\n");
      out.write("		<div style=\"text-align: center;\">\r\n");
      out.write("			<a href=\"");
      out.print( errorDocLink );
      out.write("\" class=\"doc-link\" target=\"_blank\">&#128214; View Documentation</a>\r\n");
      out.write("		</div>\r\n");
      out.write("		");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<!-- Support Section -->\r\n");
      out.write("		<div class=\"support-section\">\r\n");
      out.write("			<div class=\"support-section-title\">&#128172; Need Help?</div>\r\n");
      out.write("			<div class=\"support-section-content\">\r\n");
      out.write("				If you continue to experience issues, please contact support and provide this transaction ID:\r\n");
      out.write("				<span class=\"transaction-id\">");
      out.print( transactionId );
      out.write("</span>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<!-- Return Button -->\r\n");
      out.write("		<form ");
      out.print( (target==null)?"":("target=\"" + target + "\""));
      out.write(" method=\"post\" action='");
      out.print( request.getParameter("ErrorMessageReturn") + brandSol);
      out.write("'>\r\n");
      out.write("			<div class=\"button-container\">\r\n");
      out.write("				<input type=\"submit\" name=\"submit\" value=\"");
      out.print( button);
      out.write("\" class=\"submit-button\"/>\r\n");
      out.write("			</div>\r\n");
      out.write("		</form>\r\n");
      out.write("\r\n");
      out.write("		<!-- Timestamp -->\r\n");
      out.write("		<div class=\"timestamp\">\r\n");
      out.write("			");
      out.print( new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss z").format(new java.util.Date()) );
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
