/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.83
 * Generated at: 2026-01-13 00:48:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class IWLogin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {


// Helper function to get context-specific help message based on error code
String getErrorHelp(String code) {
    if (code == null) return null;

    if ("AUTH001".equals(code)) {
        return "&#8226; Verify your email address and password are correct<br>" +
               "&#8226; Passwords are case-sensitive<br>" +
               "&#8226; If you've forgotten your password, use the \"Change User Password\" link below<br>" +
               "&#8226; If you haven't registered, use the registration link above";
    } else if ("AUTH002".equals(code)) {
        return "&#8226; Contact your company administrator to activate your account<br>" +
               "&#8226; Check if you received an account activation email<br>" +
               "&#8226; Your account may need to be reactivated after a period of inactivity";
    } else if ("AUTH003".equals(code)) {
        return "&#8226; Contact your company administrator for assistance<br>" +
               "&#8226; Your company's subscription may have expired<br>" +
               "&#8226; Contact InterWeave support if you need immediate access";
    } else if ("DB001".equals(code)) {
        return "&#8226; Please try again in a few moments<br>" +
               "&#8226; If the problem continues, contact your system administrator<br>" +
               "&#8226; The system may be undergoing maintenance";
    } else if ("VALIDATION001".equals(code)) {
        return "&#8226; Both email and password are required to log in<br>" +
               "&#8226; Please fill in all fields before clicking Login";
    }

    return null;
}

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\">\r\n");
      out.write("<title>IW_IDE Secure Portal Login</title>\r\n");
      out.write("<style>\r\n");
      out.write(".arial12{font:Arial, Helvetica, sans-serif; font-family:Arial, Helvetica, sans-serif; font-size:12px; color:#454545; line-height:16px;}\r\n");
      out.write(".verdana10{font:verdana,Arial, sans-serif; font-family:verdana,Arial, sans-serif; font-size:10px; color:#000000; line-height:16px; font-weight:bold;}\r\n");
      out.write(".input-box{border:1px solid #000000; font:Verdana, Arial; font-family:Verdana, Arial; font-size:10px;}\r\n");
      out.write(".submit-button{border:1px solid #000000; font:Verdana, Arial; font-family:Verdana, Arial; font-size:10px; font-weight:bold; background-color:#CCCCCC;}\r\n");
      out.write(".error-msg{color:#cc0000; font-weight:bold; background-color:#ffeeee; padding:12px; border:1px solid #cc0000; margin:10px 0; border-radius:4px; font-family:Arial, sans-serif; font-size:12px;}\r\n");
      out.write(".error-msg-title{font-size:14px; margin-bottom:8px; color:#990000;}\r\n");
      out.write(".error-msg-text{font-weight:normal; line-height:18px; margin-bottom:8px;}\r\n");
      out.write(".error-msg-help{font-weight:normal; font-size:11px; background-color:#fff; padding:8px; margin-top:8px; border-left:3px solid #cc0000; color:#666;}\r\n");
      out.write(".error-code{font-family:monospace; font-size:10px; color:#999; float:right;}\r\n");
      out.write(".success-msg{color:#006600; font-weight:bold; background-color:#eeffee; padding:8px; border:1px solid #006600; margin:10px 0; border-radius:4px;}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");

String email = request.getParameter("Email");
if(email==null){
    email = "";
}
String errorMsg = request.getParameter("error");
String errorCode = request.getParameter("errorCode");
String successMsg = request.getParameter("success");
String brand = request.getParameter("PortalBrand");
if(brand==null){
    brand="";
}
String solutions = request.getParameter("PortalSolutions");
if(solutions==null){
    solutions="";
}
String brandSol = "";
if (brand != null && brand.length() > 0) {
    brandSol += "&PortalBrand=" + brand;
}
if (solutions != null && solutions.length() > 0) {
    brandSol += "&PortalSolutions=" + solutions;
}
String brandSol1 = "";
if (brand != null && brand.length() > 0) {
    brandSol1 += "?PortalBrand=" + brand;
}
if (solutions != null && solutions.length() > 0) {
    brandSol1 += ((brand != null && brand.length() > 0)?"&":"?") + "PortalSolutions=" + solutions;
}

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

String errorHelp = errorCode != null ? getErrorHelp(errorCode) : null;

      out.write("\r\n");
      out.write("<form action=\"LoginServlet\" method=\"post\">\r\n");
      out.write("<input type=\"hidden\" name=\"PortalBrand\" value=\"");
      out.print( brand);
      out.write("\"/>\r\n");
      out.write("<input type=\"hidden\" name=\"PortalSolutions\" value=\"");
      out.print( solutions);
      out.write("\"/>\r\n");
      out.write("<center>\r\n");
      out.write("  <p>&nbsp;</p>\r\n");
      out.write("  <table width=\"535\" border=\"0\" cellspacing=\"0\" cellpadding=\"10\">\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td align=\"left\"><img src=\"");
      out.print( "images" + ((brand==null || brand.equals(""))?"":("/" + brand)) + "/logo.gif");
      out.write("\" width=\"201\" height=\"43\"></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  ");
 if(errorMsg != null && !errorMsg.isEmpty()) { 
      out.write("\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td>\r\n");
      out.write("      <div class=\"error-msg\">\r\n");
      out.write("        ");
 if(errorCode != null && !errorCode.isEmpty()) { 
      out.write("\r\n");
      out.write("          <span class=\"error-code\">[");
      out.print( errorCode );
      out.write("]</span>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("        <div class=\"error-msg-title\">&#9888; Login Error</div>\r\n");
      out.write("        <div class=\"error-msg-text\">");
      out.print( errorMsg );
      out.write("</div>\r\n");
      out.write("        ");
 if(errorHelp != null) { 
      out.write("\r\n");
      out.write("        <div class=\"error-msg-help\">\r\n");
      out.write("          <strong>What to do next:</strong><br>\r\n");
      out.write("          ");
      out.print( errorHelp );
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("    </td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  ");
 } 
      out.write("\r\n");
      out.write("  ");
 if(successMsg != null && !successMsg.isEmpty()) { 
      out.write("\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td><div class=\"success-msg\">");
      out.print( successMsg );
      out.write("</div></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  ");
 } 
      out.write("\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td bgcolor=\"E7E6E3\"  style=\"border:1px solid #B2B2B2\"><table width=\"100%\"  border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td align=\"left\" class=\"arial12\" >New User? Please <a href=\"");
      out.print( "Registration.jsp" + brandSol1);
      out.write("\" class=\"arial12\">register here</a> </td>\r\n");
      out.write("        <td align=\"right\" class=\"arial12\">New Company? Please <a href=\"");
      out.print( "CompanyRegistration.jsp" + brandSol1);
      out.write("\" class=\"arial12\">register here</a></td>\r\n");
      out.write("      </tr>\r\n");
      out.write("    </table>\r\n");
      out.write("      </td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td width=\"533\" height=\"250\" background=\"images/bg.jpg\" style=\"border-left:1px solid #B2B2B2; border-right:1px solid #B2B2B2\"><table width=\"100%\"  border=\"0\" cellspacing=\"0\" cellpadding=\"24\">\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td class=\"verdana10\" align=\"left\"><p>Username<br>\r\n");
      out.write("              <input name=\"Email\" type=\"text\" maxlength=\"255\" class=\"input-box\" value='");
      out.print( email);
      out.write("'/>\r\n");
      out.write("              <br>\r\n");
      out.write("              <br>\r\n");
      out.write("            Password<br>\r\n");
      out.write("            <input name=\"Password\" type=\"password\" maxlength=\"255\" class=\"input-box\"/>\r\n");
      out.write("        <br>\r\n");
      out.write("              <br>\r\n");
      out.write("            <input type=\"submit\" name=\"submit\" value=\"Login\" class=\"submit-button\"/></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("    </table></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td bgcolor=\"E7E6E3\"  style=\"border:1px solid #B2B2B2\"><table width=\"100%\"  border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td align=\"left\" class=\"arial12\"><a href=\"ChangePassword.jsp\" class=\"arial12\">Change User Password</a><br>\r\n");
      out.write("          <a href=\"");
      out.print( "EditProfile.jsp" + brandSol1);
      out.write("\" class=\"arial12\">Edit User Profile</a><br>\r\n");
      out.write("          <a href=\"");
      out.print( "ChangeCompanyPassword.jsp" + brandSol1);
      out.write("\" class=\"arial12\">Change Company Password</a><br>\r\n");
      out.write("          <a href=\"");
      out.print( "EditCompanyProfile.jsp" + brandSol1);
      out.write("\" class=\"arial12\">Edit Company Profile</a></td>\r\n");
      out.write("        <td align=\"right\" class=\"arial12\">");
      out.print( brand.equals("")?"Return to ":"Visit ");
      out.write("Interweave Home Page<br>\r\n");
      out.write("          <a href=\"http://www.interweave.biz\" class=\"arial12\">www.interweave.biz</a></td>\r\n");
      out.write("      </tr>\r\n");
      out.write("    </table></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td align=\"center\"><img src=\"images/power.gif\" width=\"224\" height=\"27\"></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</center>\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
