/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.83
 * Generated at: 2025-12-04 22:45:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, false, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>IW_IDE Web Portal</title>\r\n");
      out.write("    <meta http-equiv=\"refresh\" content=\"0;url=/iw-business-daemon/IWLogin.jsp\">\r\n");
      out.write("    <link href=\"favicon.ico\" rel=\"icon\" type=\"image/x-icon\" />\r\n");
      out.write("    <style>\r\n");
      out.write("        body {\r\n");
      out.write("            font-family: Arial, sans-serif;\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 40px;\r\n");
      out.write("            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);\r\n");
      out.write("            min-height: 100vh;\r\n");
      out.write("        }\r\n");
      out.write("        .container {\r\n");
      out.write("            max-width: 600px;\r\n");
      out.write("            margin: 40px auto;\r\n");
      out.write("            background: white;\r\n");
      out.write("            padding: 40px;\r\n");
      out.write("            border-radius: 12px;\r\n");
      out.write("            box-shadow: 0 10px 40px rgba(0,0,0,0.2);\r\n");
      out.write("        }\r\n");
      out.write("        h1 {\r\n");
      out.write("            color: #333;\r\n");
      out.write("            margin-bottom: 10px;\r\n");
      out.write("        }\r\n");
      out.write("        .subtitle {\r\n");
      out.write("            color: #666;\r\n");
      out.write("            margin-bottom: 30px;\r\n");
      out.write("        }\r\n");
      out.write("        .redirect-msg {\r\n");
      out.write("            background: #e8f5e9;\r\n");
      out.write("            padding: 15px;\r\n");
      out.write("            border-radius: 6px;\r\n");
      out.write("            margin-bottom: 30px;\r\n");
      out.write("            color: #2e7d32;\r\n");
      out.write("        }\r\n");
      out.write("        .links {\r\n");
      out.write("            margin-top: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        .links a {\r\n");
      out.write("            display: block;\r\n");
      out.write("            padding: 14px 20px;\r\n");
      out.write("            margin: 10px 0;\r\n");
      out.write("            background: #4CAF50;\r\n");
      out.write("            color: white;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            border-radius: 6px;\r\n");
      out.write("            font-weight: 500;\r\n");
      out.write("            transition: background 0.2s;\r\n");
      out.write("        }\r\n");
      out.write("        .links a:hover {\r\n");
      out.write("            background: #43a047;\r\n");
      out.write("        }\r\n");
      out.write("        .links a.config {\r\n");
      out.write("            background: #2196F3;\r\n");
      out.write("        }\r\n");
      out.write("        .links a.config:hover {\r\n");
      out.write("            background: #1e88e5;\r\n");
      out.write("        }\r\n");
      out.write("        .links a.test {\r\n");
      out.write("            background: #ff9800;\r\n");
      out.write("        }\r\n");
      out.write("        .links a.test:hover {\r\n");
      out.write("            background: #fb8c00;\r\n");
      out.write("        }\r\n");
      out.write("        .footer {\r\n");
      out.write("            margin-top: 30px;\r\n");
      out.write("            padding-top: 20px;\r\n");
      out.write("            border-top: 1px solid #eee;\r\n");
      out.write("            color: #999;\r\n");
      out.write("            font-size: 12px;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <h1>IW_IDE Web Portal</h1>\r\n");
      out.write("        <p class=\"subtitle\">InterWeave Integration Development Environment</p>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"redirect-msg\">\r\n");
      out.write("            Redirecting to login page...\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <p>If you are not redirected automatically, select an option below:</p>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"links\">\r\n");
      out.write("            <a href=\"/iw-business-daemon/IWLogin.jsp\">Login to IW_IDE</a>\r\n");
      out.write("            <a href=\"/iw-business-daemon/BDConfigurator.jsp\" class=\"config\">Business Daemon Configurator</a>\r\n");
      out.write("            <a href=\"/iw-business-daemon/CompanyConfiguration.jsp\" class=\"config\">Company Configuration</a>\r\n");
      out.write("            <a href=\"/db_test.jsp\" class=\"test\">Database Connection Test</a>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"footer\">\r\n");
      out.write("            IW_IDE v2.41 | Apache Tomcat 9.0.83\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
